export const data = [{
    id: 0,
    title: "Good luck in court",
    author: "memesxD",
    src: "https://i.imgur.com/45A7x6i.mp4",
    views: 43732,
    upvotes: 1166,
    downvotes: 13,
    comments: [{}],
    timestamp: "",
    tags: [],
},{
    id: 1,
    title: "Keep calm",
    author: "abhimix",
    src: "https://i.imgur.com/eXBAqbH.jpg",
    views: 11247,
    upvotes: 420,
    downvotes: 9,
    comments: [{}],
    timestamp: "",
    tags: [],
},{
    id: 2,
    title: "It's the comfort I deserve",
    author: "BeFairToEveryOnePlease",
    src: "https://i.imgur.com/nINOJQ8.jpeg",
    views: 24340,
    upvotes: 1013,
    downvotes: 22,
    comments: [{}],
    timestamp: "",
    tags: [],
},{
    id: 3,
    title: "Right",
    author: "SylvaGemDriver",
    src: "https://i.imgur.com/l0Uq3Ef.jpeg",
    views: 24340,
    upvotes: 1013,
    downvotes: 22,
    comments: [{}],
    timestamp: "",
    tags: [],
},{
    id: 4,
    title: "Good luck in court",
    author: "memesxD",
    src: "https://i.imgur.com/45A7x6i.mp4",
    views: 43732,
    upvotes: 1166,
    downvotes: 13,
    comments: [{}],
    timestamp: "",
    tags: [],
},{
    id: 5,
    title: "Keep calm",
    author: "abhimix",
    src: "https://i.imgur.com/eXBAqbH.jpg",
    views: 11247,
    upvotes: 420,
    downvotes: 9,
    comments: [{}],
    timestamp: "",
    tags: [],
},{
    id: 6,
    title: "It's the comfort I deserve",
    author: "BeFairToEveryOnePlease",
    src: "https://i.imgur.com/nINOJQ8.jpeg",
    views: 24340,
    upvotes: 1013,
    downvotes: 22,
    comments: [{}],
    timestamp: "",
    tags: [],
},{
    id: 7,
    title: "Right",
    author: "SylvaGemDriver",
    src: "https://i.imgur.com/l0Uq3Ef.jpeg",
    views: 24340,
    upvotes: 1013,
    downvotes: 22,
    comments: [{}],
    timestamp: "",
    tags: [],
},{
    id: 8,
    title: "Good luck in court",
    author: "memesxD",
    src: "https://i.imgur.com/45A7x6i.mp4",
    views: 43732,
    upvotes: 1166,
    downvotes: 13,
    comments: [{}],
    timestamp: "",
    tags: [],
},{
    id: 9,
    title: "Keep calm",
    author: "abhimix",
    src: "https://i.imgur.com/eXBAqbH.jpg",
    views: 11247,
    upvotes: 420,
    downvotes: 9,
    comments: [{}],
    timestamp: "",
    tags: [],
},{
    id: 10,
    title: "It's the comfort I deserve",
    author: "BeFairToEveryOnePlease",
    src: "https://i.imgur.com/nINOJQ8.jpeg",
    views: 24340,
    upvotes: 1013,
    downvotes: 22,
    comments: [{}],
    timestamp: "",
    tags: [],
},{
    id: 11,
    title: "Right",
    author: "SylvaGemDriver",
    src: "https://i.imgur.com/l0Uq3Ef.jpeg",
    views: 24340,
    upvotes: 1013,
    downvotes: 22,
    comments: [{}],
    timestamp: "",
    tags: [],
},{
    id: 12,
    title: "Good luck in court",
    author: "memesxD",
    src: "https://i.imgur.com/45A7x6i.mp4",
    views: 43732,
    upvotes: 1166,
    downvotes: 13,
    comments: [{}],
    timestamp: "",
    tags: [],
},{
    id: 13,
    title: "Keep calm",
    author: "abhimix",
    src: "https://i.imgur.com/eXBAqbH.jpg",
    views: 11247,
    upvotes: 420,
    downvotes: 9,
    comments: [{}],
    timestamp: "",
    tags: [],
},{
    id: 14,
    title: "It's the comfort I deserve",
    author: "BeFairToEveryOnePlease",
    src: "https://i.imgur.com/nINOJQ8.jpeg",
    views: 24340,
    upvotes: 1013,
    downvotes: 22,
    comments: [{}],
    timestamp: "",
    tags: [],
},{
    id: 15,
    title: "Right",
    author: "SylvaGemDriver",
    src: "https://i.imgur.com/l0Uq3Ef.jpeg",
    views: 24340,
    upvotes: 1013,
    downvotes: 22,
    comments: [{}],
    timestamp: "",
    tags: [],
},];